name: Compile and deploy docs ğŸ“š
on:
  push:
    tags:
      - v*
jobs:
  compile-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.4.0
      - name: Compile javadoc ğŸ”§
        run: ./gradlew javadoc
      - name: Extract release âœ‚ï¸
        shell: bash
        run: echo "##[set-output name=release;]$(echo ${GITHUB_REF#refs/tags/})"
        id: extract_release
      - name: Deploy latest docs ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: docs
          folder: build/docs/javadoc
          git-config-name: Kryonite Docs
          git-config-email: docs@kryonite.org
          target-folder: latest
      - name: Deploy versioned docs ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: docs
          folder: build/docs/javadoc
          git-config-name: Kryonite Docs
          git-config-email: docs@kryonite.org
          target-folder: ${{ steps.extract_release.outputs.release }}