name: Compile and deploy docs ğŸ“š
on: [push]
jobs:
  compile-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.4
      - name: Compile javadoc ğŸ”§
        run: ./gradlew javadoc
      - name: Extract branch name âœ‚ï¸
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: docs
          folder: build/docs/javadoc
          git-config-name: Kryonite Docs
          git-config-email: docs@kryonite.org
          target-folder: ${{ steps.extract_branch.outputs.branch }}