name: Build and test ğŸ—ï¸

on: [push]

jobs:
  build-and-test:
    uses: kryonitelabs/.github/.github/workflows/build-and-test.yaml@feat/reusable-actions
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}